[package]
name = "rowan"
version = "0.10.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/rust-analyzer/rowan"
license = "MIT OR Apache-2.0"
description = "Library for generic lossless syntax trees"
edition = "2018"

[dependencies]
rustc-hash = "1.0.1"
text-size = "1.0.0"
smol_str = "0.1.10"
thin-dst = "1.0.0"

[dependencies.serde_] # renamed so feature flag can be "serde"
package = "serde"
version = "1.0.89"
optional = true
default-features = false

[dev-dependencies]
m_lexer = "0.0.4"

[features]
serde = ["serde_", "text-size/serde"]

serde1 = [ "serde" ] # deprecated alias for feature "serde"
