[package]
name = "rowan"
version = "0.3.3"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/matklad/rowan"
license = "MIT OR Apache-2.0"
description = "Library for generic lossless syntax trees."

[dependencies]
colosseum = "0.2.2"
parking_lot = "0.7.1"
text_unit = "0.1.6"
smol_str = "0.1.9"
serde = { version = "1.0.89", optional = true, features = ["serde_derive"] }

[dev-dependencies]
m_lexer = "0.0.4"
